apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
namespace: helloworld
images:
  - name: helloworld-argocd
    newName: helloworld-argocd
    newTag: v1